# Generated by Django 3.1.7 on 2021-02-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20210223_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='full_description',
            field=models.TextField(default='полное описание задания'),
            preserve_default=False,
        ),
    ]
