# Generated by Django 3.1.7 on 2021-02-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_task_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
